# Generated by Django 3.0.5 on 2021-02-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_likes'),
        ('users', '0007_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='user_liked_posts', to='blog.Post'),
        ),
    ]
