# Generated by Django 3.1.7 on 2021-03-17 10:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210317_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=users.models.uploadImg_to),
        ),
    ]
