# Generated by Django 3.1.7 on 2021-03-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210304_2322'),
        ('users', '0017_auto_20210318_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_later',
            field=models.ManyToManyField(blank=True, related_name='user_view_later_posts', to='blog.Post'),
        ),
    ]
