# Generated by Django 3.0.5 on 2020-05-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200504_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bodyy',
            new_name='body',
        ),
    ]
