# Generated by Django 3.0.5 on 2020-05-18 22:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200518_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=blog.models.uploadImg_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_path',
            field=models.FileField(blank=True, default=None, upload_to=blog.models.uploadVid_to),
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
        migrations.DeleteModel(
            name='VideoPost',
        ),
    ]
