# Generated by Django 3.0.5 on 2021-02-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210215_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('POST', 'Post'), ('VID', 'Video'), ('IMG', 'Image')], default='', max_length=30),
        ),
    ]
