from . import views
from django.urls import path, re_path
from . views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    SearchView,
    SearchUserView,
    ProfileListView,
    FollowingListView,
    FollowersListView,
    follow_unfollow_profile,
    LikePostView,
    LikedListView,
    ViewLaterView,
    ViewLaterListView,
    CategoryView,
    CategoryListView,
    Inbox,
    UserSearch,
    Directs,
    NewConversation,
    SendDirect,
    checkDirects,
    )

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/newPost/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('list/profiles/', ProfileListView.as_view(), name='profiles-list'),
    path('category/<str:cats>/', CategoryView, name='category-view'),
    path('categories/', CategoryListView, name='category-list-view'),
    path('user/<str:username>/list/following/', FollowingListView.as_view(), name='following-list'),
    path('user/<str:username>/list/followers/', FollowersListView.as_view(), name='followers-list'),
    path('switch_follow/', follow_unfollow_profile, name='follow-unfollow-view'),
    path('like/<int:pk>/<', LikePostView, name='like-post'),
    path('user/<str:username>/list/liked/', LikedListView.as_view(), name='liked-list'),
    path('view_later/<int:pk>/<', ViewLaterView, name='view-later-post'),
    path('user/<str:username>/list/ViewLater/', ViewLaterListView.as_view(), name='view-later-list'),
    re_path(r'^search/$', SearchView.as_view(), name='search_posts'),
    re_path(r'^search_user/$', SearchUserView.as_view(), name='search_profiles'),

    path('inbox', Inbox, name='inbox'),
   	path('directs/<username>', Directs, name='directs'),
   	path('new/', UserSearch, name='usersearch'),
   	path('new/<username>', NewConversation, name='newconversation'),
   	path('send/', SendDirect, name='send_direct'),
]
